logging:
  file:
    name: logs/erknm/mail-integration.log

server:
  port: 9103

spring:
  datasource:
    hikari:
      maximum-pool-size: 5
  mail:
    host: smtp.gmail.com
    port: 587
    username: www
    password: pass
    properties:
      debug: true
      smtp:
        ssl:
          trust: smtp.gmail.com
        allow8bitmime: true
        starttls:
          enable: true