logging:
  file:
    name: logs/erknm/mail-integration.log

server:
  port: 9103

spring:
  datasource:
    hikari:
      maximum-pool-size: 5
  mail:
    host: smtp.gmail.com
    port: 587
    username: website.score.analysis.tech@gmail.com
    password: 12345678qweASDZXC
    properties:
      mail:
        debug: false
        smtp:
          ssl:
            trust: smtp.gmail.com
          allow8bitmime: true
          starttls:
            enable: true

sender:
  integration:
    receive-polling-interval: 5000
    host-confirm-url: http://localhost:9102/website/confirm/