version: '3.4'

services:

  zookeeper-website:
    image: wurstmeister/zookeeper:3.4.6
    restart: unless-stopped
    container_name: zookeeper-website

  kafka-website:
    image: wurstmeister/kafka:2.12-2.4.1
    restart: unless-stopped
    container_name: kafka-website
    depends_on:
      - zookeeper-website
    environment:
      KAFKA_LISTENERS: "${KAFKA_LISTENERS}"
      KAFKA_ADVERTISED_LISTENERS: "${KAFKA_ADVERTISED_LISTENERS}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}"
      KAFKA_INTER_BROKER_LISTENER_NAME: "${KAFKA_INTER_BROKER_LISTENER_NAME}"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
      KAFKA_CREATE_TOPICS: |
        loan.request.topic:1:1
        loan.index.write.topic:1:1
        loan.response.topic:1:1
      KAFKA_ZOOKEEPER_CONNECT: "${KAFKA_ZOOKEEPER_CONNECT}"
      HOSTNAME_COMMAND: "echo '${IP_ADDRESS}'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  elasticsearch-website:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch-website
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  config-service:
    build: config-service
    restart: unless-stopped
    container_name: config-service
    environment:
      CONFIG_URL: "${CONFIG_URL}"
      CONFIG_SERVICE_PASS: "${CONFIG_SERVICE_PASS}"
      CONFIG_SERVICE_USER: "${CONFIG_SERVICE_USER}"
      DEF_JAVA_OPTIONS: "${DEF_JAVA_OPTIONS}"

  website-service:
    build: website-service
    restart: unless-stopped
    container_name: website-service
    depends_on:
      - config-service
    environment:
      CONFIG_URL: "${CONFIG_URL}"
      CONFIG_SERVICE_PASS: "${CONFIG_SERVICE_PASS}"
      CONFIG_SERVICE_USER: "${CONFIG_SERVICE_USER}"
      DEF_JAVA_OPTIONS: "${DEF_JAVA_OPTIONS}"

  website-ml-service:
    build: website-ml-service
    restart: unless-stopped
    container_name: website-ml-service
    depends_on:
      - config-service
    environment:
      CONFIG_URL: "${CONFIG_URL}"
      CONFIG_SERVICE_PASS: "${CONFIG_SERVICE_PASS}"
      CONFIG_SERVICE_USER: "${CONFIG_SERVICE_USER}"
      DEF_JAVA_OPTIONS: "${DEF_JAVA_OPTIONS}"

  mail-integration-service:
    build: mail-integration-service
    restart: unless-stopped
    container_name: mail-integration-service
    depends_on:
      - config-service
    environment:
      CONFIG_URL: "${CONFIG_URL}"
      CONFIG_SERVICE_PASS: "${CONFIG_SERVICE_PASS}"
      CONFIG_SERVICE_USER: "${CONFIG_SERVICE_USER}"
      DEF_JAVA_OPTIONS: "${DEF_JAVA_OPTIONS}"

  liquibase-service:
    build: liquibase-service
    container_name: liquibase-service
    depends_on:
      - config-service
    environment:
      CONFIG_URL: "${CONFIG_URL}"
      CONFIG_SERVICE_PASS: "${CONFIG_SERVICE_PASS}"
      CONFIG_SERVICE_USER: "${CONFIG_SERVICE_USER}"
      DEF_JAVA_OPTIONS: "${DEF_JAVA_OPTIONS}"

  index-write-service:
    build: index-write-service
    restart: unless-stopped
    container_name: index-write-service
    depends_on:
      - config-service
    environment:
      CONFIG_URL: "${CONFIG_URL}"
      CONFIG_SERVICE_PASS: "${CONFIG_SERVICE_PASS}"
      CONFIG_SERVICE_USER: "${CONFIG_SERVICE_USER}"
      DEF_JAVA_OPTIONS: "${DEF_JAVA_OPTIONS}"

  index-sync-service:
    build: index-sync-service
    restart: unless-stopped
    container_name: index-sync-service
    depends_on:
      - config-service
    environment:
      CONFIG_URL: "${CONFIG_URL}"
      CONFIG_SERVICE_PASS: "${CONFIG_SERVICE_PASS}"
      CONFIG_SERVICE_USER: "${CONFIG_SERVICE_USER}"
      DEF_JAVA_OPTIONS: "${DEF_JAVA_OPTIONS}"

  index-read-service:
    build: index-read-service
    restart: unless-stopped
    container_name: index-read-service
    depends_on:
      - config-service
    environment:
      CONFIG_URL: "${CONFIG_URL}"
      CONFIG_SERVICE_PASS: "${CONFIG_SERVICE_PASS}"
      CONFIG_SERVICE_USER: "${CONFIG_SERVICE_USER}"
      DEF_JAVA_OPTIONS: "${DEF_JAVA_OPTIONS}"