version: '3.4'

services:
  zookeeper-website:
    ports:
      - 2181:2181
    networks:
      - public-website

  kafka-website:
    ports:
      - 9092:9092
      - 19092:19092
    networks:
      - public-website
  elasticsearch-website:
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - public-website
  config-service:
    ports:
      - 9101:9101
    networks:
      - public-website
  website-service:
    ports:
      - 9102:9102
    networks:
      - public-website
  website-ml-service:
    ports:
      - 9104:9104
    networks:
      - public-website
  mail-integration-service:
    ports:
      - 9103:9103
    networks:
      - public-website
  index-write-service:
    ports:
      - 9106:9106
    networks:
      - public-website
  index-sync-service:
    ports:
      - 9107:9107
    networks:
      - public-website
  index-read-service:
    ports:
      - 9105:9105
    networks:
      - public-website

volumes:
  elasticsearch-data:
    driver: local

networks:
  public-website: