<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Панель Администратора</title>
</head>
<body>
<a href="/website/admin/news" methods="get">
    <button type="button">Перейти к новостям</button>
</a>
<p></p>
<a href="/website/admin/users" methods="get">
    <button type="button">Перейти к пользователям</button>
</a>
<p></p>
<a href="/website/main" methods="get">
    <button type="button">Главная</button>
</a>
<p></p>
<a href="/website/logout" methods="get">
    <button type="button">Выйти</button>
</a>
<p></p>
</body>
</html>