<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Добро пожаловать</title>
</head>
<body>
<h3><b>Здесь вы сможете быстро получить кредит для своей компании</b></h3>
<p></p>
<a href="/website/auth/signIn" methods="get">
    <button type="button">Войти</button>
</a>
<p></p>
<a href="/website/auth/signUp" methods="get">
    <button type="button">Зарегистрироваться</button>
</a>
</body>
</html>